version: "4.2"
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0.4
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: start-dev

  postgres:
    container_name: postgres
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_DB: master
      POSTGRES_USER: postgresadmin
      POSTGRES_PASSWORD: P0stgres@dm1n
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    driver: local